### ISSUE TITLE
Stable cursor position

### ISSUE THREAD

**Issue by takaxp** [alphapapa/org-recent-headings#1]
Hi.

Thank to providing nice tool! My small suggestion is to add `(move-beginning-of-line 1)` to the last line of `org-recent-headings--show-entry` so that user can move the cursor by `n/p` between headings without moving the cursor to the beginning of the line, and many users also could call `org-cycle(TAB)` as well.

Best,
Takaaki

**Comment by alphapapa** [comment]
Thanks, that's a great idea!  I'll add it soon.  :)
