### ISSUE TITLE
org-recent-headings-helm: "Invalid function: helm-build-sync-source"

### ISSUE THREAD

**Issue by tenpast** [alphapapa/org-recent-headings#15]
Hi Alphapapa,

Intrigued by your recent workflow screenshot I decided to go through your `alpha-org` configuration and use some of your configurations. One of the packages I installed is your `org-recent-headings` package with the configuration provided in `alpha-org`. When running the `org-recent-headings-helm` function, emacs returns "Invalid function: helm-build-sync-source."

I've tried running `emacs -q` with the following init:

    (require 'package)

    (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)

    (package-initialize)

    (eval-and-compile
    	    (setq
	     use-package-always-ensure t
	     use-package-enable-imenu-support t
	     use-package-compute-statistics t))

    (eval-when-compile
      (require 'use-package))

    (use-package helm)

    (use-package org-recent-headings
      :config
      (org-recent-headings-mode)
      :custom
      (org-recent-headings-reverse-paths t)
      (org-recent-headings-candidate-number-limit 100))

I run the code, expression by expression, without errors, then when I run the `org-recent-headings` `use-package` declaration, I get:

    Debugger entered--Lisp error: (invalid-function helm-build-sync-source)
      helm-build-sync-source(" Recent Org headings" :candidates #f(compiled-function () #<bytecode 0x158ff2f0586d>) :candidate-number-limit org-recent-headings-candidate-number-limit :candidate-transformer org-recent-headings--truncate-candidates :keymap (keymap (C-return . org-recent-headings--show-entry-indirect-helm-action) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap (describe keymap (describe-mode . helm-help)))) (help keymap (109 . helm-help)) (23 . #f(compiled-function () (interactive nil) #<bytecode 0x158ff34a76d9>)) (f1 lambda nil (interactive) (helm-select-nth-action 0)) (8 keymap (109 . helm-help) (104 . undefined) (8 . undefined) (99 . helm-customize-group) (4 . helm-enable-or-switch-to-debug)) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap (57 . helm-execute-selection-action-at-nth-+9) (56 . helm-execute-selection-action-at-nth-+8) (55 . helm-execute-selection-action-at-nth-+7) (54 . helm-execute-selection-action-at-nth-+6) (53 . helm-execute-selection-action-at-nth-+5) (52 . helm-execute-selection-action-at-nth-+4) (51 . helm-execute-selection-action-at-nth-+3) (50 . helm-execute-selection-action-at-nth-+2) (49 . helm-execute-selection-action-at-nth-+1) (63 . helm-help) (110 . #f(compiled-function () (interactive nil) #<bytecode 0x158ff34a7685>)) (108 . helm-display-line-numbers-mode) (62 . helm-toggle-truncate-line) (21 . helm-refresh) (6 . helm-follow-mode) (9 . helm-copy-to-buffer) (11 . helm-kill-selection-and-quit) (25 . helm-yank-selection) (37 . helm-exchange-minibuffer-and-header-line) (95 . helm-toggle-full-frame) (45 . helm-swap-windows)) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (24 keymap (57 . helm-execute-selection-action-at-nth-+9) (56 . helm-execute-selection-action-at-nth-+8) (55 . helm-execute-selection-action-at-nth-+7) (54 . helm-execute-selection-action-at-nth-+6) (53 . helm-execute-selection-action-at-nth-+5) (52 . helm-execute-selection-action-at-nth-+4) (51 . helm-execute-selection-action-at-nth-+3) (50 . helm-execute-selection-action-at-nth-+2) (49 . helm-execute-selection-action-at-nth-+1) (2 . helm-resume-list-buffers-after-quit) (98 . helm-resume-previous-session-after-quit) (6 . helm-quit-and-find-file)) (11 . helm-delete-minibuffer-contents) (67108896 . helm-toggle-visible-mark-forward) (0 . helm-toggle-visible-mark) (C-M-up . helm-scroll-other-window-down) (C-M-down . helm-scroll-other-window) (M-prior . helm-scroll-other-window-down) (M-next . helm-scroll-other-window) (12 . helm-recenter-top-bottom-other-window) (left . helm-previous-source) (right . helm-next-source) (15 . helm-next-source) (10 . helm-execute-persistent-action) (9 . helm-select-action) (13 . helm-maybe-exit-minibuffer) (7 . helm-keyboard-quit) (22 . helm-next-page) (27 keymap (110 . next-history-element) (112 . previous-history-element) (115 . undefined) (5 . helm-display-all-sources) (1 . helm-show-all-candidates-in-source) (85 . helm-unmark-all) (97 . helm-mark-all) (109 . helm-toggle-all-marks) (41 . helm-next-visible-mark) (40 . helm-prev-visible-mark) (91) (32 . helm-toggle-visible-mark-backward) (33554454 . helm-scroll-other-window-down) (25 . helm-scroll-other-window-down) (22 . helm-scroll-other-window) (12 . helm-reposition-window-other-window) (111 . helm-previous-source) (62 . helm-end-of-buffer) (60 . helm-beginning-of-buffer) (118 . helm-previous-page)) (next . helm-next-page) (prior . helm-previous-page) (C-up . helm-follow-action-backward) (C-down . helm-follow-action-forward) (16 . helm-previous-line) (14 . helm-next-line) ...) :action (("Show entry (default function)" . org-recent-headings--show-entry-default) ("Show entry in real buffer" . org-recent-headings--show-entry-direct) ("Show entry in indirect buffer" . org-recent-headings--show-entry-indirect) ("Remove entry" . org-recent-headings-helm-remove-entries) ("Bookmark heading" . org-recent-headings--bookmark-entry)))
      #f(compiled-function () #<bytecode 0x158ff2f05929>)()
      eval-after-load(helm #f(compiled-function () #<bytecode 0x158ff2f05929>))
      byte-code("\300\301\302\"\210\300\303\304\"\207" [eval-after-load helm #f(compiled-function () #<bytecode 0x158ff2f05929>) ivy #f(compiled-function () #<bytecode 0x158ff2f05955>)] 3)
      require(org-recent-headings nil t)
      (not (require 'org-recent-headings nil t))
      (if (not (require 'org-recent-headings nil t)) (display-warning 'use-package (format "Cannot load %s" 'org-recent-headings) :error) (use-package-statistics-gather :config 'org-recent-headings nil) (condition-case err (progn (org-recent-headings-mode) t) ((debug error) (funcall use-package--warning2 :config err))) (use-package-statistics-gather :config 'org-recent-headings t))
      (progn (funcall (or (get 'org-recent-headings-reverse-paths 'custom-set) #'set-default) 'org-recent-headings-reverse-paths t) (funcall (or (get 'org-recent-headings-candidate-number-limit 'custom-set) #'set-default) 'org-recent-headings-candidate-number-limit 100) (use-package-statistics-gather :init 'org-recent-headings nil) (if (not (require 'org-recent-headings nil t)) (display-warning 'use-package (format "Cannot load %s" 'org-recent-headings) :error) (use-package-statistics-gather :config 'org-recent-headings nil) (condition-case err (progn (org-recent-headings-mode) t) ((debug error) (funcall use-package--warning2 :config err))) (use-package-statistics-gather :config 'org-recent-headings t)) (use-package-statistics-gather :init 'org-recent-headings t))
      (condition-case err (progn (funcall (or (get 'org-recent-headings-reverse-paths 'custom-set) #'set-default) 'org-recent-headings-reverse-paths t) (funcall (or (get 'org-recent-headings-candidate-number-limit 'custom-set) #'set-default) 'org-recent-headings-candidate-number-limit 100) (use-package-statistics-gather :init 'org-recent-headings nil) (if (not (require 'org-recent-headings nil t)) (display-warning 'use-package (format "Cannot load %s" 'org-recent-headings) :error) (use-package-statistics-gather :config 'org-recent-headings nil) (condition-case err (progn (org-recent-headings-mode) t) ((debug error) (funcall use-package--warning2 :config err))) (use-package-statistics-gather :config 'org-recent-headings t)) (use-package-statistics-gather :init 'org-recent-headings t)) ((debug error) (funcall use-package--warning2 :catch err)))
      (progn (use-package-statistics-gather :use-package 'org-recent-headings nil) (use-package-ensure-elpa 'org-recent-headings '(t) 'nil) (defvar use-package--warning2 #'(lambda (keyword err) (let ((msg (format "%s/%s: %s" ... keyword ...))) (display-warning 'use-package msg :error)))) (condition-case err (progn (funcall (or (get 'org-recent-headings-reverse-paths 'custom-set) #'set-default) 'org-recent-headings-reverse-paths t) (funcall (or (get 'org-recent-headings-candidate-number-limit 'custom-set) #'set-default) 'org-recent-headings-candidate-number-limit 100) (use-package-statistics-gather :init 'org-recent-headings nil) (if (not (require 'org-recent-headings nil t)) (display-warning 'use-package (format "Cannot load %s" 'org-recent-headings) :error) (use-package-statistics-gather :config 'org-recent-headings nil) (condition-case err (progn (org-recent-headings-mode) t) ((debug error) (funcall use-package--warning2 :config err))) (use-package-statistics-gather :config 'org-recent-headings t)) (use-package-statistics-gather :init 'org-recent-headings t)) ((debug error) (funcall use-package--warning2 :catch err))) (use-package-statistics-gather :use-package 'org-recent-headings t))
      eval((progn (use-package-statistics-gather :use-package 'org-recent-headings nil) (use-package-ensure-elpa 'org-recent-headings '(t) 'nil) (defvar use-package--warning2 #'(lambda (keyword err) (let ((msg ...)) (display-warning 'use-package msg :error)))) (condition-case err (progn (funcall (or (get 'org-recent-headings-reverse-paths 'custom-set) #'set-default) 'org-recent-headings-reverse-paths t) (funcall (or (get 'org-recent-headings-candidate-number-limit 'custom-set) #'set-default) 'org-recent-headings-candidate-number-limit 100) (use-package-statistics-gather :init 'org-recent-headings nil) (if (not (require 'org-recent-headings nil t)) (display-warning 'use-package (format "Cannot load %s" 'org-recent-headings) :error) (use-package-statistics-gather :config 'org-recent-headings nil) (condition-case err (progn (org-recent-headings-mode) t) ((debug error) (funcall use-package--warning2 :config err))) (use-package-statistics-gather :config 'org-recent-headings t)) (use-package-statistics-gather :init 'org-recent-headings t)) ((debug error) (funcall use-package--warning2 :catch err))) (use-package-statistics-gather :use-package 'org-recent-headings t)) nil)
      elisp--eval-last-sexp(nil)
      eval-last-sexp(nil)
      funcall-interactively(eval-last-sexp nil)
      call-interactively(eval-last-sexp nil nil)
      command-execute(eval-last-sexp)

Output of `M-x emacs-version`:
`Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-29`

Any idea what can be causing this? 

Thank you for your help and as always, for the useful and interesting packages and commentary. I've started using Burly recently with good results :+1: 

Best Regards,
TenPast

**Comment by alphapapa** [comment]
Hi,

I think that should fix it.  Please let me know if it works for you now.

Thanks for reporting, and thanks for the kind words.  Please keep the feedback coming.  :)

**Comment by tenpast** [comment]
Yes, that did the trick! Thank you :)

**Comment by alphapapa** [comment]
@tenpast  FYI, this change absolutely broke it for me.  I can't explain why.  Anyway, it seemed like the only thing to do was, finally, to split the Helm code into a separate package.  So: https://github.com/alphapapa/org-recent-headings/commit/fda7a0ce356c6ecc88d93bc373fbd2f31106eb8a

**Comment by tenpast** [comment]
Thanks for the heads-up. I'm sorry to see that my problem opened up a can of worms but happy to know you've found a solution. 

I couldn't find helm-org-recent-headings on `Melpa`. I tried your `quelpa` recipe and received the following error:

    Debugger entered--Lisp error: (error "Package ‘helm-org-recent-headings-’ is unavailable")
      signal(error ("Package ‘helm-org-recent-headings-’ is unavailable"))
      error("Package `%s-%s' is unavailable" helm-org-recent-headings "")
      package-compute-transaction(nil ((helm-org-recent-headings)))
      package-install(helm-org-recent-headings)
      use-package-ensure-elpa(helm-org-recent-headings (t) nil)
      (progn (use-package-statistics-gather :use-package 'helm-org-recent-headings nil) (use-package-ensure-elpa 'helm-org-recent-headings '(t) 'nil) (if (and quelpa-use-package-inhibit-loading-quelpa (package-installed-p 'helm-org-recent-headings)) nil (apply 'quelpa '((helm-org-recent-headings :fetcher github :repo "alphapapa/org-recent-headings" :files ("helm-org-recent-headings.el"))))) (defvar use-package--warning113 #'(lambda (keyword err) (let ((msg (format "%s/%s: %s" ... keyword ...))) (display-warning 'use-package msg :error)))) (condition-case err (progn (use-package-statistics-gather :init 'helm-org-recent-headings nil) (if (not (require 'helm-org-recent-headings nil t)) (display-warning 'use-package (format "Cannot load %s" 'helm-org-recent-headings) :error) (use-package-statistics-gather :config 'helm-org-recent-headings nil) (use-package-statistics-gather :config 'helm-org-recent-headings t)) (use-package-statistics-gather :init 'helm-org-recent-headings t)) ((debug error) (funcall use-package--warning113 :catch err))) (use-package-statistics-gather :use-package 'helm-org-recent-headings t))
      eval((progn (use-package-statistics-gather :use-package 'helm-org-recent-headings nil) (use-package-ensure-elpa 'helm-org-recent-headings '(t) 'nil) (if (and quelpa-use-package-inhibit-loading-quelpa (package-installed-p 'helm-org-recent-headings)) nil (apply 'quelpa '((helm-org-recent-headings :fetcher github :repo "alphapapa/org-recent-headings" :files ("helm-org-recent-headings.el"))))) (defvar use-package--warning113 #'(lambda (keyword err) (let ((msg ...)) (display-warning 'use-package msg :error)))) (condition-case err (progn (use-package-statistics-gather :init 'helm-org-recent-headings nil) (if (not (require 'helm-org-recent-headings nil t)) (display-warning 'use-package (format "Cannot load %s" 'helm-org-recent-headings) :error) (use-package-statistics-gather :config 'helm-org-recent-headings nil) (use-package-statistics-gather :config 'helm-org-recent-headings t)) (use-package-statistics-gather :init 'helm-org-recent-headings t)) ((debug error) (funcall use-package--warning113 :catch err))) (use-package-statistics-gather :use-package 'helm-org-recent-headings t)) nil)
      elisp--eval-last-sexp(nil)
      eval-last-sexp(nil)
      funcall-interactively(eval-last-sexp nil)
      call-interactively(eval-last-sexp nil nil)
      command-execute(eval-last-sexp)

I have no previous experience with `quelpa`, but I think I followed the correct instructions for both `quelpa` and `use-package-quelpa`. Any advise would be welcome.

Finally, (sorry, this is the wrong repository) I meant to ask you what you bound `just-one-space` to after taking `M-SPC` over for alpha-org keybindings (a very practical prefix by the way). I make extensive use of `just-one-space` and wonder if you do as well. If you do not, what's your work around. I mostly use it when I have space at the beginning of a line and would like to get rid of it.

Thanks again.

**Comment by alphapapa** [comment]
> I couldn't find helm-org-recent-headings on `Melpa`. I tried your `quelpa` recipe and received the following error:

I just went through the whole process again in a clean Emacs installation and it worked.  Try again; that error may be transient.



> Finally, (sorry, this is the wrong repository) I meant to ask you what you bound `just-one-space` to after taking `M-SPC` over for alpha-org keybindings (a very practical prefix by the way). I make extensive use of `just-one-space` and wonder if you do as well. If you do not, what's your work around. I mostly use it when I have space at the beginning of a line and would like to get rid of it.

```
(defun ap/cycle-spacing ()
  (interactive)
  (cycle-spacing -1))
```

**Comment by tenpast** [comment]
Thanks for your quick response! 

> I just went through the whole process again in a clean Emacs installation and it worked. Try again; that error may be transient.

It works now when I install it from `Melpa`. I must have been doing something wrong when using `Quelpa` and `Quelpa-use-package`. I'll go back when I have some time and read the docs as they look like useful packages.

> ```
> (defun ap/cycle-spacing ()
>   (interactive)
>   (cycle-spacing -1))
> ```
This is an interesting little function. A value of `1` is what `just one space` would give me (which was not ideal). A value of `0` is what I find most useful (remove all space and place first letter at beginning of line). A value of -1 seems useful to join two paragraphs maybe? Is that what you use it for? What is your keybinding for it?

Thanks again :)

**Comment by alphapapa** [comment]
See the docstring for the details.  I just mash it until I get the result I want.  Don't overthink it.
