### ISSUE TITLE
frecency min requirement too high

### ISSUE THREAD

**Issue by progfolio** [alphapapa/org-recent-headings#22]
It looks like freecency.el has only published [version 0.1-pre](https://github.com/alphapapa/frecency.el/blob/5b04e109969846a51207f6d6de77a9fcdfdddf98/frecency.el#L7).
Whereas org-recent-headings depends on a min version of 0.1.
This will cause installation of org-recent-headings to fail on Elpaca.

**Comment by alphapapa** [comment]
Just pushed v1.0 of `frecency`: https://github.com/alphapapa/frecency.el/commit/4293bf4c8d571b0914e16a5aa05a6d657fdff551  Should fix it.  Thanks.
