### ISSUE TITLE
Bug: when creating a new empty header you get a error buffer: Warning (emacs): org-recent-headings: Heading is empty, oops.  Please report this bug.

### ISSUE THREAD

**Issue by zeltak** [alphapapa/org-recent-headings#4]
Hi

i cant reproduce this bug

type a new empty header (star `*`) then press SPACE then press Enter

you get this error in a pop up buffer

``` Warning (emacs): org-recent-headings: Heading is empty, oops.  Please report this bug.``

the *messages* buffer shows this

```org-recent-headings--store-heading: Wrong type argument: stringp, t```

can you confirm this on your machine?

Z

**Comment by alphapapa** [comment]
Thanks, that was an oversight on my part.  Your feedback is invaluable!
