### ISSUE TITLE
FYI: New version 0.2

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/org-recent-headings#9]
@zeltak Hey there my friend, hope you're doing well.  FYI, I just pushed a new version of this package.  It mainly improves the code, but it also adds a new feature.   https://github.com/alphapapa/org-recent-headings#02-pre  If you're interested, please try it out and let me know how it works for you.

An important note is that the list format changed.  I included code to convert it automatically, and it seems to work in my testing, so it should work for other users.  But in case you have a lot of important headings saved in your recent-headings list, you might want to back up the save file before testing the new version, because if conversion fails, the old list might be lost.

**Comment by zeltak** [comment]
awesome!

how are you @alphapapa? Im moving to the us for a job this week so I will try it next week and report back!

thx again for you awesome work, its appreciated daily!

Z

**Comment by zeltak** [comment]
hi @alphapapa 

so finally had a chance to test it and everything seems to work well!

thx again for all your awesome work :)
z

**Comment by alphapapa** [comment]
Thanks for your help!  And welcome to the USA.  :)
